dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- pypy
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
- pypy3
install:
- pip install pydiatra pyflakes
script:
- python -m pydiatra .
- pyflakes .
- PYTHONPATH=$PWD python test/test.py --verbose
- LC_ALL=C python setup.py --version
- python setup.py install
- cd /
- python -c 'import slownie'
- curl -fsS https://pypi.python.org/simple/slownie/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
